name: CI/CD Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          cache: gradle

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install hadolint
        run: |
            wget -O hadolint "https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64" && \
            chmod +x hadolint && \
            sudo mv hadolint /usr/local/bin/hadolint

      - name: Run hadolint
        run: hadolint Dockerfile

      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.myfirsttoken}} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
