name: CI/CD Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          cache: gradle

      - name: Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build with Gradle
        run: ./gradlew build

      - name: Hadolint
        run: |
          docker build -t hadolint-check .
          docker run --rm hadolint-check
